title: Open Hydroponics RO
description: Informații, ghiduri și protocoale pentru cultivarea plantelor în sisteme hidroponice (Kratky, DWC, etc.) adaptate pentru România.
theme: jekyll-theme-midnight
url: "https://laurencedeer.github.io"
baseurl: "/protocoale-hydroponics"

# Setări vizuale
show_downloads: false
google_analytics: 

# Plugin-uri
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Setări Markdown 
markdown: kramdown
kramdown:
  input: GFM
